# Generated by Django 2.1.3 on 2018-11-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='id_movie',
            new_name='id_advert',
        ),
    ]
