# Generated by Django 2.1.3 on 2018-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0002_auto_20181201_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
