# Generated by Django 2.1.3 on 2018-11-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0002_auto_20181113_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='amout_available',
            new_name='amount_available',
        ),
    ]
