# Generated by Django 2.1.3 on 2018-11-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0003_auto_20181113_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
