# Generated by Django 2.1.3 on 2018-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0004_auto_20181113_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='id_advert',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='vendor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
