# Generated by Django 2.1.3 on 2018-11-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0005_auto_20181113_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='url',
        ),
    ]
