# Generated by Django 2.1.3 on 2018-11-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0006_remove_advert_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='id_advert',
            field=models.IntegerField(),
        ),
    ]
