# Generated by Django 2.1.3 on 2018-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0008_auto_20181113_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='url_poster',
            field=models.CharField(default='', max_length=300),
        ),
    ]
