# Generated by Django 2.1.3 on 2018-11-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0009_advert_url_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='url_poster',
            new_name='photo_url',
        ),
    ]
