# Generated by Django 2.1.3 on 2018-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallafood', '0010_auto_20181126_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo_url',
            field=models.CharField(default='https://www.telemundo.com/sites/nbcutelemundo/files/images/promo/video_clip/2017/12/21/frutas-y-verduras.jpg', max_length=300),
        ),
    ]
